[colors]

background = "#282828"
foreground = "#ebdbb2"
cursor_bg = "#ebdbb2"
cursor_fg = "#282828"
cursor_border = "#ebdbb2"
selection_bg = "#a9b1d6"
selection_fg = "#c0caf5"
nansi = [
    "#282828",
    "#cc241d",
    "#98971a",
    "#d79921",
    "#458588",
    "#b16286",
    "#689d6a",
    "#a89984",
]
brights = [
    "#928374",
    "#fb4934",
    "#b8bb26",
    "#fabd2f",
    "#83a598",
    "#d3869b",
    "#8ec07c",
    "#ebdbb2",
]

[colors.indexed]

[metadata]

aliases = []
name = "Gruvbox Dark (Gogh)"
origin_url = "https://github.com/Gogh-Co/Gogh"
