[colors]
ansi = [
    "#101010",
    "#e84f4f",
    "#b8d68c",
    "#e1aa5d",
    "#7dc1cf",
    "#9b64fb",
    "#6d878d",
    "#dddddd",
]
background = "#151515"
brights = [
    "#404040",
    "#d23d3d",
    "#a0cf5d",
    "#f39d21",
    "#4e9fb1",
    "#8542ff",
    "#42717b",
    "#dddddd",
]
foreground = "#d7d0c7"

[colors.indexed]

[metadata]
aliases = []
author = "crshd"
name = "X::DotShare (terminal.sexy)"
